<template>
  <!-- Chart Labels -->
  <dl :class="base.wrapper">
    <div
      v-for="(label, index) of labelData"
      :class="base.item"
      :key="`${chartName}-${index}`"
    >
      <dt :class="[base.key, label.className]">{{label.value}}%</dt>
      <dd :class="base.value">{{label.labelText}}</dd>
    </div>
  </dl>
</template>

<script>

export default {
  name: 'ChartLabel',
  props: {
    chartName: {
      type: String,
      required: true
    },
    labelData: {
      type: Array,
      required: true
    }
  }
}
</script>

<style lang="scss" module="base">
@import '~styleConfig/color';

$chart-light-gray: color('light', $grade: -10);

.wrapper {
  composes: paddingVerticalBetweenXnarrow from 'styles/spacing.scss';
  display: block;

  // try to make webkit/chrome print background colors here
  -webkit-print-color-adjust: exact;
}

.item {
  display: block;
}

.key {
  $size: 3.5em;
  composes: white from 'styles/color.scss';
  composes: scaleEta bold from 'styles/type.scss';
  display: inline-block;
  border-radius: 50%;
  width: $size;
  height: $size;
  text-align: center;
  vertical-align: middle;
  line-height: $size;
}

.value {
  composes: scaleZeta from 'styles/type.scss';
  display: inline-block;
  margin-left: 0.5em;
  vertical-align: middle;
}

// classes generated by DataMethods.getChartData() and passed in with label data
:global {
  .supply,
  .la-fourniture {
    fill: $chart-light-gray;
    stroke: $chart-light-gray;
    background-color: $chart-light-gray;
    color: color('dark');
  }

  .demand,
  .demande {
    fill: color('accent');
    stroke: color('accent');
    background-color: color('accent');
    color: color('white');
  }

  .enabling-environment,
  .environnement-habilitant {
    fill: color('highlight');
    stroke: color('highlight');
    background-color: color('highlight');
    color: color('white');
  }

  .coordination {
    fill: color('primary');
    stroke: color('primary');
    background-color: color('primary');
    color: color('white');
  }

  .youth-centric {
    fill: color('primary');
    stroke: color('primary');
    background-color: color('primary');
    color: color('white');
  }

  .not-youth-centric {
    fill: $chart-light-gray;
    stroke: $chart-light-gray;
    background-color: $chart-light-gray;
    color: color('dark');
  }
}
</style>
